# These are supported funding model platforms

custom:
  # Bitcoin (BTC) – legacy, segwit & taproot addresses all work
  - "bitcoin:bc1qyourbitcoinaddresshere?label=YourProject&message=GitHub%20donation"

  # Ethereum (ETH) + ERC-20 tokens (USDT, USDC, etc. – send directly to same address)
  - "ethereum:0xYourEthereumAddressHere?label=YourProject&message=GitHub%20donation%20(ETH/USDT/USDC)"

  # Solana (SOL)
  - "solana:YourSolanaAddressHere?label=YourProject&message=GitHub%20donation"

  # XRP (Ripple) – include ?dt= if using destination tag, otherwise plain
  - "https://xrpl.org/?yourxrpaddresshere?label=YourProject"   # xrpl: URI not widely supported → use explorer/link or plain

  # Dogecoin (DOGE)
  - "dogecoin:DYourDogecoinAddressHere?label=YourProject&message=GitHub%20donation"

  # Cardano (ADA)
  - "https://cardano.org/?YourCardanoAddressHere"   # cardano: URI not standard → use link or plain address

  # Bitcoin Cash (BCH)
  - "bitcoincash:bitcoincash:qzYourBCHAddressHere?label=YourProject&message=GitHub%20donation"

  # Litecoin (LTC)
  - "litecoin:LYourLitecoinAddressHere?label=YourProject&message=GitHub%20donation"

  # Zcash (ZEC) – shielded (z) or transparent (t) – shielded preferred for privacy
  - "zcash:zsYourZcashShieldedAddressHere?label=YourProject&message=GitHub%20donation"

  # Sui (SUI)
  - "https://sui.io/?YourSuiAddressHere"   # sui: URI not widely adopted → use explorer link

# Optional: one aggregator page that lists ALL addresses nicely (highly recommended)
  - "https://coindrop.to/yourusername"           # or buymeacoffee / your own page
